Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'mccalc_1sym_1snps.R': No such file or directory
Execution halted
srun: error: compute-0-0: task 0: Exited with exit code 1
